name: Deploy Static Site

on:
  push:
    branches: [main] 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload artifact (optional)
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: .  
